version: '3.7'

services:
  web:
    configs:
      - source: NGINX_CONFIG
        target: /etc/nginx/conf.d/default.conf
      - source: NGINX_HTML
        target: /usr/share/nginx/html/index.html
    deploy:
      mode: global
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 10
        window: 120s

  server:
    image: shahandocker1986/ts-app-server:0.0.1
    command: npm run start
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 10
        window: 120s

  mysqldb:
    configs:
      - source: MYSQL_HEALTHECHECK
        target: /usr/local/bin/healthcheck.sh
        mode: 555
    deploy:
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 10
        window: 120s
      placement:
        constraints:
          - node.role == manager
    volumes:
      - mysql_prod:/var/lib/mysql

volumes:
  mysql_prod:
    driver: local

networks:
  app:
    driver: overlay

configs:
  MYSQL_HEALTHECHECK:
    file: ../healthchecks/mysql-healthcheck.sh
    name: MYSQL_HEALTHECHECK_20220924T035300
  NGINX_CONFIG:
    file: ../nginx/default.conf
    name: NGINX_CONFIG_20220924T035300
  NGINX_HTML:
    file: ../nginx/default.html
    name: NGINX_HTML_20220924T035300
