version: '3.7'

services:
  web:
    deploy:
      mode: global
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 10
        window: 120s
    depends_on:
      - server
    networks:
      - app
    image: 127.0.0.1:5000/ts-app-web
    ports:
      - 80:80

  server:
    image: 127.0.0.1:5000/ts-app-server
    command: npm run start
    volumes:
      - ../uploads:/app/uploads:rw
      - ../logs:/app/logs:rw
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 10
        window: 120s

  mysqldb:
    image: 127.0.0.1:5000/ts-app-mysql
    deploy:
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 10
        window: 120s
    volumes:
      - mysql_prod:/var/lib/mysql

volumes:
  mysql_prod:
    driver: local

networks:
  app:
    driver: overlay
