version: '3.7'

services:
  server:
    tty: true
    depends_on:
      mysqldb:
        condition: service_healthy
    build:
      context: ../
      target: test
    restart: 'no'
    command: npm run exec-tests

  mysqldb:
    tty: true
    restart: 'no'
    volumes:
      - mysql_test:/var/lib/mysql
      - ../healthchecks/mysql-healthcheck.sh:/usr/local/bin/healthcheck.sh

volumes:
  mysql_test:
    driver: local

networks:
  app:
    driver: bridge
